### ISSUE TITLE
502 Bad Gateway on initial request

### ISSUE THREAD

**Issue by pingec** [AeonLucid/POGOLib#2]
Firstly, of all the C# repos I have checked out, this code is by far the most readable so thank you a lot for the effort.

I would like to login through the example but I am having some difficulties, perhaps someone can point out what I could be doing wrong?

When the client does the first, inital request (through the GetApiEndPoint method) to "https://pgorelease.nianticlabs.com/plfe/rpc"  the following response is received
```
{StatusCode: 502, ReasonPhrase: 'Bad Gateway', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Alt-Svc: clear
  Connection: close
  Date: Wed, 20 Jul 2016 00:59:34 GMT
  Content-Length: 332
  Content-Type: text/html; charset=UTF-8
}}
```

Which then triggers an exception when parsing on this line https://github.com/AeonLucid/POGOLib/blob/98f514ef5f552ad998b6ea0fc3d9bc0a353fedb9/POGOLib/Net/RPCClient.cs#L165

```
Google.Protobuf.InvalidProtocolBufferException was unhandled
  HResult=-2146232800
  Message=SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
  Source=Google.Protobuf
  StackTrace:
       at Google.Protobuf.CodedInputStream.SkipLastField()
       at POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStream input) in D:\node_dev\POGOLib\POGOLib\POGOProtos\Networking\Envelopes\ResponseEnvelope.cs:line 293
       at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, Byte[] data)
       at Google.Protobuf.MessageParser`1.ParseFrom(Byte[] data)
       at POGOLib.Net.RpcClient.SendRemoteProtocolCall(String apiUrl, Request request) in D:\node_dev\POGOLib\POGOLib\Net\RpcClient.cs:line 303
       at POGOLib.Net.RpcClient.GetApiEndpoint() in D:\node_dev\POGOLib\POGOLib\Net\RpcClient.cs:line 53
       at POGOLib.Net.RpcClient..ctor(PoClient poClient) in D:\node_dev\POGOLib\POGOLib\Net\RpcClient.cs:line 39
       at POGOLib.Net.PoClient.OnAuthenticated(Object sender, EventArgs eventArgs) in D:\node_dev\POGOLib\POGOLib\Net\PoClient.cs:line 238
       at POGOLib.Net.PoClient.OnAuthenticated(EventArgs e) in D:\node_dev\POGOLib\POGOLib\Net\PoClient.cs:line 244
       at POGOLib.Net.PoClient.Authenticate(String password) in D:\node_dev\POGOLib\POGOLib\Net\PoClient.cs:line 132
       at Demo.Program.Main(String[] args) in D:\node_dev\POGOLib\Demo\Program.cs:line 73
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

This happens with ptc and google login.

I also tried updating to latest proto definitions, but the problem remains. There are some magic numbers involved when sending requests and perhaps those are being set incorrectly?

**Comment by pingec** [comment]
Ok I have solved it, here is the pull request https://github.com/AeonLucid/POGOLib/pull/4
