### ISSUE TITLE
startup StartupAsync() returns false. 

### ISSUE THREAD

**Issue by drunkenhammer** [AeonLucid/POGOLib#58]
When you start the heartbeat to refresh map data
session.StartupAsync() returns false 40% of the time.

**Comment by jahknee** [comment]
I encounter this too, very often. Here's more details:

18:13:15  Debug   Authenticated from cache.
18:13:16  Debug   Sending RPC Request: 'GetPlayer, CheckChallenge'
18:13:16  Info    Unknown status code: SessionInvalidated
18:13:16  Error   SendRemoteProcedureCall exception: System.Exception: There were 0 responses.
   at POGOLib.Official.Net.RpcClient.HandleResponseEnvelope(RequestEnvelope requestEnvelope, ResponseEnvelope responseEnvelope)
   at POGOLib.Official.Net.RpcClient.<PerformRemoteProcedureCallAsync>d__32.MoveNext()
