### ISSUE TITLE
Throw ArgumentNullException when calling RefreshMapObjectsAsync method in sometime

### ISSUE THREAD

**Issue by EagleTsui** [AeonLucid/POGOLib#60]
This issue some time will be triggered, I don't know what problem, sometime the map.Cells is not null
Here is my code
var loginProvider = new PtcLoginProvider("test", "123456");
var session = await Login.GetSession(loginProvider, 22.412557, 113.983121);
await session.StartupAsync();
await session.RpcClient.RefreshMapObjectsAsync(); <- sometime will trigger error

My case is sometime it will be work, sometime throw ArgumentNullException
here is exception detail
{System.ArgumentNullException: Value cannot be null.
Parameter name: data
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at Google.Protobuf.MessageParser`1.ParseFrom(ByteString data)
   at POGOLib.Official.Net.RpcClient.<RefreshMapObjectsAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Pogo.Program.<Run>d__2.MoveNext() in C:\Users\eagletsui\Documents\Source\Test\Pogo\Program.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Pogo.Program.Main(String[] args) in C:\Users\eagletsui\Documents\Source\Test\Pogo\Program.cs:line 30}

**Comment by EagleTsui** [comment]
Sometime trigger this issue is current IP is USA but the 22.412557, 113.983121 location is hong kong, so the pokemon server reject this ip.
